### ISSUE TITLE
Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

### ISSUE THREAD

**Issue by onurbaser** [Yenthe666/InstallScript#126]
First of thank you very much Yenthe for this script.

When I create a fresh new database I got "Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^" 

it goes  to /web/database/selector page
There is a exclamation mark and it says "This Database may not be compatible"

In this server I am running Odoo10 + Odoo11 which were created by Yenthe Scripts. And also with a new username and new port for each instance. This may be not related with script but just in case if you have any idea.
Ubuntu Linux 16.04.1
PostgreSQL version 9.5.14

**Comment by Yenthe666** [comment]
Hi @onurbaser,

Looks pretty similar to https://github.com/Yenthe666/InstallScript/issues/73
Some people reported there that PSQL 9.6 or above solved this so you might want to try that first.

**Comment by foxeslover** [comment]
For me using postgresql 9.3 or 9.4, review the log file i saw:

> 2018-10-15 00:53:16,357 12493 ERROR hrmdemo odoo.sql_db: bad query: b"\n                INSERT INTO ir_model_data (module, name, model, res_id, noupdate, date_init, date_update)\n                VALUES ('base', 'field_base__display_name', 'ir.model.fields', 2, false, now() at time zone 'UTC', now() at time zone 'UTC'), ('base', 'field_base____last_update', 'ir.model.fields', 3, false, now() at time zone 'UTC', now() at time zone 'UTC'), ('base', 'field_base__id', 'ir.model.fields', 1, false, now() at time zone 'UTC', now() at time zone 'UTC')\n                ON CONFLICT (module, name)\n                DO UPDATE SET date_update=(now() at time zone 'UTC') \n            "
> ERROR: syntax error at or near "ON"
> LINE 4:                 ON CONFLICT (module, name)
>                         ^

ON CONFLICT keyword just from postgresql v9.5 so i think for odoo v12 we have to use postgresql v9.5 or above. Hope that info will help.

**Comment by Yenthe666** [comment]
Yep, absolutely.

**Comment by onurbaser** [comment]
Thank you so much. I will update my ubuntu to 18 LTS which includes PostgreSQL 9.6 as you suggested...

**Comment by onurbaser** [comment]
Well I was not able to update ubuntu 16.04.1 LTS to 18 LTS (do-release-upgrade and with switch -d do not work, it says no new relase, althought at login it says new relase available ;-) )).

So I manually upgraded to 9.6 and now it works! Thank you for your help.

**Comment by Yenthe666** [comment]
Good to hear - you're welcome!

**Comment by prajithpipt** [comment]
I meet the same Issue

Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

I am using 'Postgres-10' in  'CentOS 7' for odoo 12 CE
but the database was created successfully in the backend, cannot access by UI

![Screenshot (15)](https://user-images.githubusercontent.com/30921111/60173541-9f4b3580-982c-11e9-967b-61943534e2e8.png)


Please help me to fix this issue

**Comment by j0xFF** [comment]
@prajithpipt could you fix it yet?

**Comment by diversemix** [comment]
I have the same issue... this is what I did on my Ubuntu 18.04 laptop:
- cloned the `odoo/odoo` repository
- within the new folder I ran `sudo python3 setup.py install` 
- I configured up my locally running postgres v10.12 to have an odoo user
- I ran `odoo -w odoo` noticed the addons were missing so linked them with ones I'd cloned from git.
```
rm -rf ${HOME}/.local/share/Odoo/addons/13.0
ln -s ${HOME}/dev/odoo/addons ${HOME}/.local/share/Odoo/addons/13.0
```
- The command `odoo -w odoo` works fine now - however on creating a new database I received exactly the same errors as above :expressionless: 

/cc @j0xFF @Yenthe666

**Comment by BabyLoves** [comment]
> I have the same issue... this is what I did on my Ubuntu 18.04 laptop:
> 
> * cloned the `odoo/odoo` repository
> * within the new folder I ran `sudo python3 setup.py install`
> * I configured up my locally running postgres v10.12 to have an odoo user
> * I ran `odoo -w odoo` noticed the addons were missing so linked them with ones I'd cloned from git.
> 
> ```
> rm -rf ${HOME}/.local/share/Odoo/addons/13.0
> ln -s ${HOME}/dev/odoo/addons ${HOME}/.local/share/Odoo/addons/13.0
> ```
> 
> * The command `odoo -w odoo` works fine now - however on creating a new database I received exactly the same errors as above 😑
> 
> /cc @j0xFF @Yenthe666

You fixed it?
I'm using PostgreSQL 13 and macOS Big Sur and I have the same issue in the Odoo 13.0
<img width="847" alt="image" src="https://user-images.githubusercontent.com/65966239/103237000-2519d680-4925-11eb-8bf0-eaf58bd960f8.png">

**Comment by off-ini** [comment]
I have the same issue on Elementary OS 5 (Linux), Postgres 10 and for odoo 14

**Comment by enricm2** [comment]
I also have the same issue with Debian 10 and postgredql 11.

**Comment by saeed-raeisi** [comment]
check postgres user and permission 
i check res_partner_view -> <field name="state_id" class="o_address_state" placeholder="State" options="{'no_open': True, 'no_quick_create': True}"

**Comment by saeed-raeisi** [comment]
check postgres user and permission 
i check res_partner_view -> <field name="state_id" class="o_address_state" placeholder="State" options="{'no_open': True, 'no_quick_create': True}"

**Comment by lushtech** [comment]
I solved this problem by this way:
**First step:**
Modify the odoo-server.conf, let the dbfilter default value  ".*" to  "^%d$" . And then restart  odoo.
**Second step:**
Through the web to create new database.
![odoo-create](https://user-images.githubusercontent.com/46964559/127758495-8ac63875-4182-4878-a68b-f83c6fb05b55.PNG)

-----------------------------------------------------------------------------------------------------------------------------
My deployment environment：

- Rancher v2.5.5(a platform of managing multiple Kubernetes clusters )
- odoo:13.0.20210110-debian-10(more information please look for github.com/bitnami/bitnami-docker-odoo.git)
- postgresql:11.10.0-debian-10-r24(more information please look for github.com/bitnami/bitnami-docker-postgresql.git)

the problem is same as other people's:
Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual'
And , I check the odoo logs when create the database:
 `
2021-08-01 03:05:44,519 1760 INFO ? werkzeug: 172.16.226.12 - - [01/Aug/2021 03:05:44] "GET /web/database/selector HTTP/1.1" 200 - 6 0.007 0.045 
2021-08-01 03:05:46,495 1760 INFO None odoo.service.db: Create database `mytest`. 
2021-08-01 03:05:47,771 1760 INFO mytest odoo.modules.loading: loading 1 modules... 
2021-08-01 03:05:47,929 1760 INFO mytest odoo.modules.registry: module base: creating or updating database tables 
2021-08-01 03:05:48,282 1760 INFO mytest odoo.models: Computing parent_path for table ir_ui_menu... 
2021-08-01 03:05:49,385 1760 INFO mytest odoo.models: Computing parent_path for table res_partner_category... 
.......
.......
2021-08-01 03:06:00,999 1760 INFO mytest odoo.modules.loading: loading base/data/res_currency_rate_demo.xml 
2021-08-01 03:06:01,415 1760 INFO mytest odoo.modules.loading: loading base/data/res_bank_demo.xml 
2021-08-01 03:06:01,425 1760 INFO mytest odoo.modules.loading: loading base/data/res_partner_demo.xml 
2021-08-01 03:06:01,748 1760 INFO mytest odoo.modules.loading: loading base/data/res_partner_image_demo.xml 
2021-08-01 03:06:02,284 1760 INFO ? odoo.sql_db: ConnectionPool(used=3/count=10/max=64): Closed 2 connections to 'user=bn_odoo password=xxx dbname=mytest host=odoo-lusha-759zb-postgresql port=5432 sslmode=prefer' 
2021-08-01 03:06:02,288 1760 INFO ? werkzeug: 172.16.226.12 - - [01/Aug/2021 03:06:02] "GET /web/database/selector HTTP/1.1" 200 - 8 7.761 0.056 
2021-08-01 03:06:02,297 1760 WARNING mytest odoo.modules.loading: Transient module states were reset 
2021-08-01 03:06:02,298 1760 ERROR mytest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last): 
  File "/opt/bitnami/odoo/odoo/api.py", line 745, in get 
    value = self._data[field][record._ids[0]] 
KeyError: 116 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/bitnami/odoo/odoo/fields.py", line 1004, in __get__ 
    value = env.cache.get(record, self) 
  File "/opt/bitnami/odoo/odoo/api.py", line 751, in get 
    raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('ir.module.module(116,).name', None) 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 364, in load_modules 

.......
.......

`
