### ISSUE TITLE
Deinstallation script

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/InstallScript#13]
For the future:

A script that cleans and removes the whole Odoo environment made with the installation script.
@sebastian-code and @tvibliani is this something you guys think would be a nice extra too?
I think I'd like one to clean up my test environments easily.

**Comment by sebastian-code** [comment]
Actually I was thinking in something like this, not just to make a clean slate, but also than validate if there are prerequisites already met.

**Comment by sebastian-code** [comment]
And if you like a real challenge, why not to implement an updating and upgrading functionality? wink wink

**Comment by Yenthe666** [comment]
@sebastian-code challenge? I love those.
I have something very limited at the moment that does what I need for now:
```
#!/bin/bash
OE_USER="odoo8"
OE_HOME="/$OE_USER"
OE_HOME_EXT="/$OE_USER/$OE_USER-server"
OE_VERSION="8.0"
#Change from user
echo "sudo su $OE_USER"
#Navigate in the correct Odoo
echo "cd $OE_HOME_EXT"
cd $OE_HOME_EXT
echo "git pull origin $OE_VERSION"
git pull origin $OE_VERSION -a
```

Very small, but this does in essence what you mean I assume? :smile:

**Comment by sebastian-code** [comment]
In a nutshell yes, it implement the updating, I would think than the upgrading is far more difficult. The only change than I would suggest is tho change the line than logs in the user in the shell, that's because the change I suggested, when you create a system user, that user has no shell, so to remedy that when needed you use `sudo su - odoo -s /bin/bash`

But actually I would say than the script does not need to login as the odoo user.

**Comment by Yenthe666** [comment]
Closing this one in favor of the newer one at https://github.com/Yenthe666/InstallScript/issues/67
