### ISSUE TITLE
Add Nginx support in installation script

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/InstallScript#17]
We should add the Nginx ability in the installation script.
This allows us to configure Nginx proxy for Odoo(s).
Commands:

```
sudo apt-get install nginx
sudo service nginx start
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo nano /etc/nginx/conf.d/openerp.conf
```

Add the following code in the file:

```
#worker_processes  1;

#events {
#    worker_connections  1024;
#}

    server {
        listen  80;
        server_name 127.0.0.1;
        location /socket.io {
            proxy_pass   http://127.0.0.1:8080;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_redirect off;
         }

        location / {
            proxy_pass   http://127.0.0.1:8080;
        }
    }
```

Finally, restart Nginx:

```
sudo service nginx restart
```

This should convert a running Odoo on port 8080 to running on port 80 (http://localhost)

@sebastian-code and @tvibliani  what do you guys think about this? I'd like input / ideas on this! I was thinking about adding a new variable at the top `OE_NGINX` which has the options `True` and `False`. When the user fills in `True` we'll install Nginx, configure it and create a new file? We'd also need a new variable to know to which port the Nginx should forward.

**Comment by Yenthe666** [comment]
@sebastian-code and @tvibliani I made a mock-up script, just for testing purposes.
What do you guys think about this one? It installs Nginx if needed, it removes the default configuration and creates a new file under ```/etc/nginx/conf.d/``` with the name of the variable ```OE_HOME_EXT```.
Every Odoo instance will have a different configuration file under ```/etc/nginx/conf.d/``` so that they are always separated and easy to modify.
Example shell script:
```
OE_HOME_EXT="odoo-server-test2"
OE_PORT="8080"

NGINX_LISTEN_PORT="6060"
echo "------Nginx checks / installation------"
if ! which nginx > /dev/null 2>&1; then
    echo "Installing and configuring Nginx"
    sudo apt-get install nginx
    sudo service nginx start
    #Remove default config file
    sudo rm /etc/nginx/sites-enabled/default
    sudo service nginx restart
else
    echo "Nginx is already installed!"
fi

#Create configuration file
sudo cat <<EOF > /etc/nginx/conf.d/$OE_HOME_EXT.conf
    server {
        listen  $NGINX_LISTEN_PORT;
        server_name 127.0.0.1;
        location /socket.io {
            proxy_pass   http://127.0.0.1:$OE_PORT;
            proxy_http_version 1.1;

            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host \$host;

            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_redirect off;
         }

        location / {
            proxy_pass   http://127.0.0.1:$OE_PORT;
        }
    }
EOF
#Restart the Nginx service
sudo service nginx restart
```

Note to self: port checking has to be built!

**Comment by sebastian-code** [comment]
Hey @Yenthe666 @tvibliani I would say than the advantage of working with Nginx is having the chance to implement also SSL, and perhaps that's something than we should to consider to implement, because if not, why should we bother ourselves deploying a proxy server, if we are not going to use SSL

I know than perhaps not much people has the intent, nor the money to keep up with the SSL certificate fee, but you actually could use a self signed certificate, what is a little problem because of the "self signed" part, and the amount of messages you're going to receive in your browser.

I thinked that, but then _voila_, I found this not so little guy https://github.com/letsencrypt/letsencrypt, from the people of https://letsencrypt.org/ and everything went in a better way.

**Comment by sebastian-code** [comment]
And about the script, I think the script is just right, at this point lacks the SSL encryption part, but that's understandable taking in consideration what I said before.

The only thing than still bothers me is than I would prefer to have an smaller bash scritp and the needed configuration files apart, and to process them, but I haven't been able to find a way to do it.

**Comment by sebastian-code** [comment]
To add a little bit of information about the convenience of installing Nginx, I should include something I missed, Odoo in the documentation actually recommends to use a static HTTP server to serve the static content in production.

For that porpoise we need to know than Odoo static files live in each module's static/ folder, so static files can be served by intercepting all requests to /MODULE/static/FILE, and looking up the right module (and file) in the various addons paths. That said, I'm not that Nginx-esque fluent to include that part into the script.

**Comment by Yenthe666** [comment]
@sebastian-code thanks for your feedback! I just don't understand what you mean with the last part about the /MODULE/static/FILE :confused: 

By the way, I also included checks to check if the file already exists yes or no and if the port is already used by another application. Script version 2:
```
OE_HOME_EXT="odoo-server-test2"
OE_PORT="8080"
NGINX_LISTEN_PORT="6060"

echo "------Starting Nginx configuration------"
#Check if Nginx is already installed. If it isn't we will install it
if ! which nginx > /dev/null 2>&1; then
    echo "Installing and configuring Nginx"
    sudo apt-get install nginx
    sudo service nginx start
    #Remove default config file
    sudo rm /etc/nginx/sites-enabled/default
    sudo service nginx restart
else
    echo "Nginx is already installed!"
fi

#Check if the Nginx configuration file doesn't exist yet
FileAlreadyExists="False"
if [ -e "/etc/nginx/conf.d/$OE_HOME_EXT.conf" ];
then
   FileAlreadyExists="True"
else
   FileAlreadyExists="False"
fi

#Check if the port is used or not
PortAlreadyUsed="False"
if nc -w 5 -z 127.0.0.1 $NGINX_LISTEN_PORT 2>/dev/null
    then
    #echo "Port is already used"
    PortAlreadyUsed="True"
    else
    #echo "Port is not yet used"
    PortAlreadyUsed="False"
fi

#Check if the port is not yet opened
if [ $PortAlreadyUsed = "True" ] || [ $FileAlreadyExists = "True" ]
    then
    echo "!!! Aborting installation !!!"
        if [ $PortAlreadyUsed = "True" ];
	    then
                echo "Port $NGINX_LISTEN_PORT is already used!"
	fi
	if [ $FileAlreadyExists = "True" ];
	    then
		echo "There is already a configuration file with this name!"
	fi
    else

#Create configuration file
sudo cat <<EOF > /etc/nginx/conf.d/$OE_HOME_EXT.conf
    server {
        listen  $NGINX_LISTEN_PORT;
        server_name 127.0.0.1;
        location /socket.io {
            proxy_pass   http://127.0.0.1:$OE_PORT;
            proxy_http_version 1.1;

            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host \$host;

            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_redirect off;
         }

        location / {
            proxy_pass   http://127.0.0.1:$OE_PORT;
        }
    }
EOF
fi
#Restart the Nginx service
sudo service nginx restart
```

Thoughts? A special note on this line:
```
if nc -w 5 -z 127.0.0.1 $NGINX_LISTEN_PORT 2>/dev/null
```
Adding [ ] to this will break the script / logic. No idea why but it will not find used ports, so I kept it this way!
And I do agree that we need SSL on it.. I just don't know how to configure that :sob:

**Comment by sebastian-code** [comment]
About the /MODULE/static/FILE part, in the Nginx config file we need to include a line to intercept the traffic addressed to those paths. Perhaps wildcards to monitor every static folder and serve that content.

And for the SSL, I included some links in the main thread to post than talks about that, this two:

http://www.schenkels.nl/2014/12/reverse-proxy-with-odoo-8-nginx-ubuntu-14-04-lts/
http://www.nkr1ptd.com/2014/11/using-nginx-with-odoo-version-8-on.html

**Comment by sebastian-code** [comment]
About this I want to add than perhaps the configuration script is not adequate for the traffic administration, en exchange I would suggest something more of the type:
´´´
## odoo backend ##
upstream odoo {
    server 127.0.0.1:8069;
}

## http site##
server {
    listen      80 default;
    server_name plan.mobius.net.co;

    # log files
    access_log  /var/log/nginx/odoo.access.log;
    error_log   /var/log/nginx/odoo.error.log;

    # proxy buffers
    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    ## default location ##
    location / {
        proxy_pass  http://odoo;
        # force timeouts if the backend dies
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;

        # set headers
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto https;
    }

    # cache some static data in memory for 60mins
    location ~* /web/static/ {
        proxy_cache_valid 200 60m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo;
    }
}
´´´
But keep in mind than still is not perfect and needs a little bit of work. About the other parts of the process, reading how to configure nginx, they say than you should create a new configuration file inside the folder ´/etc/nginx/sites-available/' with the script content. After that you have to enable the new site configuration by creating a symbolic link in the ´/etc/nginx/sites-enabled/´ folder.

**Comment by lukebranch** [comment]
@Yenthe666 ,

Have you added any support for domain > db routing? I think this would be a great addition to the script.

I'll try and fork your current master script and make some changes to submit a PR later for you to take a look at. I think a step to allow for domain/DB mapping in the setup script, as well as a separate script to allow for the setup of nginx domain > db mapping might be useful for those who are not so familiar with the process.

**Comment by Yenthe666** [comment]
@sebastian-code I'll try to test these things in a few days, a bit too busy at the moment..
@lukebranch there is no support for domain > db routing, I do not have enough knowledge for this I think.
Could you explain a bit more about the setup and what you would suggest to do? 
As for the forking and making a PR: there are still other PR's and changes waiting for me, so give me a few days to fix and merge those in? This would improve quite some things to the current script :+1:

**Comment by lukebranch** [comment]
@Yenthe666 ,

My schedule is pretty tight at the moment so I won't be submitting PR's anytime soon unfortunately, however i'll come back here and fill out my explanation of what I mean for the Nginx domain > db routing as soon as I can find some time.

It shouldn't be too hard to setup, and I think would come in very handy for those with multiple databases /domains hosted on one server.

**Comment by Yenthe666** [comment]
@lukebranch agreed on your multiple databases / domains hosted on one server. I'll wait for more information and details :+1: 
Let us combine our knowledge & power to make something great together.

**Comment by sebastian-code** [comment]
I'm not sure. but I would guess than @lukebranch is talking about an Odoo multi-tenant system, basically a single Odoo system may run and serve a number of database instances (a.k.a. one server serving multiple companies). I only would point out than this kind of setup is perhaps a _nice to have_, given the fact than most people will deploy their Odoo instance over their own machine or on a VPS. But out there have to be scenarios were SysAdmins would need something like this.

Using this kind of configuration is not an issue when working with the backend (web client) as a logged-in company user because the database can be selected when logging in, and the respective customizations will be loaded afterwards. However it think this is an issue for non-logged users (portal, website) which aren't bound to a database, that happens because Odoo need to know which database should be used for the operations or to get the data.

My question would be if the intent is to implement the `--db-filter`flag? Because I don't know how to use the Nginx proxy setup to include the dynamically injected hostname or subdomain through which the Odoo system is accessed.

**Comment by lukebranch** [comment]
@sebastian-code ,

Yes, this is definitely a nice-to-have feature, and not an absolute must for the average joe who just wants to install Odoo for one company/website.

With that being said i've come across the need myself to deploy a number of setups like this, and I will be building this feature to add to my own personal scripts to save me time when deploying new setups. 

I prefer to encapsulate these kinds of routine jobs into scripts to cut down on the time for deploying new setups, and it saves me having to remember every little detail about how to setup a particular reporting engine, proxy config, etc. if I can just distill that knowledge in a script and come back to it when I need it.

In my nginx configuration (eg. /etc/nginx/sites-available/exampledomain.com) I have the following within the server { } tags:

    proxy_set_header X-ODOO-dbfilter MyExampleDatabaseName;

where MyExampleDatabaseName is the exact name of the database i'm using. You'll also need the module dbfilter_from_header:

https://github.com/OCA/server-tools/tree/8.0/dbfilter_from_header

accessible by Odoo by adding the module's path to your addons_path = in your /etc/odoo-server.conf file.

Public users would be redirected to the correct database based on the domain they arrive on, for example, exampledomain.com would point to exampledatabase and would act like a single database instance of Odoo that would not prompt the user to select a database.

I forget the exact thread, but there is a lengthy discussion about this in the community mailing lists that you may find useful that explains it in a bit more detail.

I'll post back when I can find time with an in-depth explanation and an example nginx configuration file so that you can take a look.

For my own use I plan to add this as a modular part of the installation script to allow a kind of yes/no logic and looping construct in the installation script that could prompt for things like whether you want to install Nginx as a reverse proxy, and prompt you with a loop for adding domain to db mapping during the setup process.

This along with adding some basic server hardening to the script (eg. SSH hardening) would make it quite useful I think for the average guy who wants to deploy Odoo for a basic website + ERP without a massive amount of sysadmin knowledge.

**Comment by sebastian-code** [comment]
That's great @lukebranch I think it will be a good thing if you take a tour around the different issues and read them, your insights will be very valuable to the improving process of the script.

**Comment by lukebranch** [comment]
@sebastian-code ,

Thanks, i'll definitely take a look around the various issues when I can find some time.

@Yenthe666 ,

What do you think about modularising the scripts for dependencies, do you think it would be better to pile all the installation logic into one .sh file, or split it into multiple separate .sh files and just call the modular .sh files from the main base script?

I'm thinking it might make the modular parts more re-usable if we split them into separate .sh files in subdirectories, for example:

/InstallScript/odoo_install.sh
/InstallScript/reporting/aeroo/aeroo_dep.sh
/InstallScript/reporting/pentaho_dep.sh
/InstallScript/repositories/OCA/...   (auto-clone the entire OCA repo list during installation)

I can certainly modularize my Aeroo Script in this fashion, as I wrote it with modularity in mind originally for my original fork of @aschenkels-ictstudio 's script.

I think this type of arrangement will allow unlimited additions of dependencies over time while keeping the main install script base lean.

I think it may also be worthwhile adding an option for postgreSQL version into the script. 9.5 GM will be released this month, and it solves a bunch of async issues for people working with large data sets in Odoo 8/9, and it may be worth giving people the option to target 9.3/9.4/9.5 and leave room for new versions as they are released.

**Comment by Yenthe666** [comment]
@lukebranch,

Well this has some benefits and downsides. The thing is that if we would modularise this script it would in essence mean that we would get multiple ```.sh``` files and that they have to be in a folder. This would also mean that the scripts and the whole proces would become more complex for somebody with little Linux / Odoo knowledge.

While I agree that the concept is interesting of having a modular approach but in usuability I think it would scare people off or it would make things more complex. I think another approach, which should also work, is to create some sort of modularity inside one script? I was thinking about something along the lines of having some variables at the top of the script like this:

```
INSTALL_AEROO="True"
INSTALL_ODOO="True"
CONFIGURE_NGINX="True"
```

Depending of them being answered with yes or no influences if a part is triggered or not. For example when ```INSTALL_AEROO``` would be ```True``` then the Aeroo part of the script would be executed, otherwise it wouldn't.
This would have the benefit of having one script to rule everything and that you would need barely any knowledge about anything. You only need to set some variables to True or False!
I'd like feedback about this though, this is just my idea.

As for the ```PostgreSQL``` 9.5 version, thanks for notifying me about this! Could you give me a bit more details about exactly what it fixes regarding async issues with large data sets in Odoo 8/9? Are there any issue reports about this or something? Either way we could add the ability to specify your ```postgreSQL``` version, shouldn't be too much of an hassle to write.

And as a final note, I decided to take your Aeroo installation script and started cleaning/tweaking it. You can find it here: https://github.com/Yenthe666/AerooInstallScript for now it doesn't seem to be 100% correct and working but its a work in progress. You're always free to try it / give feedback / ...
Eventually this script will be merged in my script for the Odoo installation so we get a modular approach.

**Comment by sebastian-code** [comment]
I would say than I'm with @lukebranch in this setup, actually is not that bad idea, and I disagree about the complexity issue. Actually a really big script is more of a problem for the maintainer, and for the final user is transparent to have an script named `playme.sh` and a bunch of accompanying files for every specific functionality. As an example look at the actual code how much is uglyfied (I think I just invented that word) and how much longer and complex results the spaghetti part of the daemon configuration file for system.d, when you can take that part aside.

I'm not really fluent in bash and I come from the Python world, so I'm used to have a lot of small scripts to do specific things, which helps to keep under control things, and don't makes you wander around the IDE looking for a line of code. And I'm also not a fan of functional programming :wink: :wink:

Taking those aside, I would like to see information about the specifics of that issue with PostgreSQL < 9.5, because what you refer sounds like a not that normal usage case for Odoo, and additionally, we have to keep in mind which version does Odoo recommend for a deployment in a production environment.

**Comment by Yenthe666** [comment]
@sebastian-code and @lukebranch I've found some guy its repo with an Nginx script so I decided to copy and slightly modify this.
Original source: https://github.com/halybang/odoo_install/blob/9.0/odoo_nginx.sh
Our script: https://github.com/Yenthe666/InstallScript/blob/master/nginx_install.sh

Thoughts? Feedback? Suggestions?
I tried the script with the following command:
```
sudo ./nginx_script.sh test.erphanoi.com Aeroo
```
Which translates to create an HTTPS connection and reverse proxy on the url test.erphanoi.com for the database Aeroo.

**Comment by sebastian-code** [comment]
The problem with this is than there is no consideration about those who already has their own expensive, previously paid SSL certificate.

**Comment by Yenthe666** [comment]
@sebastian-code you mean that there should be an ability to re-purpose an already bought SSL cert? So that if they have bought it before it could be merged in this? I honestly have no idea how I should script that. SSL certs are quite of a blank space in my knowledge.

**Comment by sebastian-code** [comment]
@Yenthe666 the truth be said, me neither, but perhaps there is room for a manual approach for the SysAdmin who is using the script to deploy the software. But that would be like install Nginx without SSL, leaving to him the SSL certificate setup.

**Comment by gustavovalverde** [comment]
Maybe you guys @Yenthe666  @sebastian-code would like to have look at this code https://github.com/gustavovalverde/odoo-install-scripts

**Comment by Yenthe666** [comment]
Thanks a lot for the heads up @gustavovalverde!
I'll be sure to look at it when I've got some spare time. 👍

**Comment by lukebranch** [comment]
has anyone played around with whiptail? I feel like it might be useful with this script once you start including things like nginx, reporting engines, etc. 

I think it could come in handy if you're open to the idea of modularising the script somewhat @Yenthe666 .

**Comment by Yenthe666** [comment]
@lukebranch,

Thanks for the suggestion, this actually does look quite nice. At the moment the script requires you to fill in the correct lines in the file itself but dialogs are probably even better.
Would you like to create a new issue with a little bit more content? I'll label it as wishlist and I'll keep it there as a reminder for myself.
Might be something that'll get added

**Comment by lukebranch** [comment]
@Yenthe666 ,

Sure, no problem, i'll create a new issue. If I can find some spare time i'll create a PR. Should I target the master branch for something like that?

**Comment by lukebranch** [comment]
that sounds like a really good idea.

**Comment by chris001** [comment]
* Yes to Lets Encrypt SSL.  
* Yes to NGINX reverse proxy.  
* These 2 options should be enabled by default in this odoo installer script.  Advanced users can disable these options, when they're running a more exotic web proxy, and/or want to use a costly paid SSL cert.

**Comment by Yenthe666** [comment]
@chris001 agreed. It all comes down to finding time to code & test all of it I guess. 😄 I've been behind on quite a lot of things lately.

**Comment by chris001** [comment]
@Yenthe666 I hear you.  I think the Ansible roles and playbooks should help with the installing of an nginx SSL reverse proxy, and getting the Lets Encrypt certs. The work is already done on them.

Otherwise, scripts already exist for obtaining Lets Encrypt certs and installing them into a running nginx server.  `certbot-auto` does this.

**Comment by Yenthe666** [comment]
Basic script for Nginx in place since https://github.com/Yenthe666/InstallScript/commit/775ee313fa197059e9cd3a87e5d3ab2718577294
