### ISSUE TITLE
Upgrade from v12 to v13

### ISSUE THREAD

**Issue by sel-carlitos** [Yenthe666/InstallScript#179]
Hi guys,
This is not really an issue but more a question. I installed v12 Enterprise Edition successfully. The script works beautiful!!! And now that v13 is out, I want to upgrade my server from v12 to v13. Is it that simple to just run  `sudo ./odoo_install.sh` after updating the script per the instructions?

Thanks, 

Carlos

**Comment by sel-carlitos** [comment]
I just realized that it's also possible to update within the same version. How does that work with this script?

**Comment by Yenthe666** [comment]
@izotecarlitos this script does not update within a current version. If you'd run the script again with the same parameters your previous install will be overwritten and you'll get into trouble.
If you want to install an Odoo 13 and modify the parameters so that it gets another location and system user it'll work just fine ;)
