### ISSUE TITLE
./odoo_install_debian.sh: line 159: [: 14.0: unary operator expected

### ISSUE THREAD

**Issue by AhmedHaroon999** [Yenthe666/InstallScript#277]
on Ubuntu 18.04 Desktop, have following output showing "14.0: unary operator expected " is it ok or something wrong with script? 

---- Setting permissions on home folder ----
* Create server config file
* Creating server config file
_./odoo_install_debian.sh: line 159: [: 14.0: unary operator expected_
* Create startup file
* Create init file
* Security Init File
* Start ODOO on Startup
Nginx isn't installed due to choice of the user!
* Starting Odoo Service
Starting odoo-server: odoo-server.

**Comment by Yenthe666** [comment]
Hmm, that is odd. We fixed this ages ago in https://github.com/Yenthe666/InstallScript/commit/62ad7239d012feb35c61d286a9679b18bbd9d707 
The fix is still there in V14 too:
https://github.com/Yenthe666/InstallScript/blob/03d3db69d415201c3a52a2b356d6b2a196a85a12/odoo_install.sh#L164

Sure you didn't modify anything that broke it?
