### ISSUE TITLE
Install Enterprise Version

### ISSUE THREAD

**Issue by ricardocolonia** [Yenthe666/InstallScript#343]
How do I install enterprise version, I have the license and I have it downloaded locally, but when I use the script it asks for github authentication, and it won't let it install.

**Comment by Yenthe666** [comment]
Add your Github user on your partner portal at odoo.com/my :) Untill you cannot access github.com/odoo/enterprise you cannot use our scripts.

**Comment by Darkmanzoro** [comment]
GooD morning @Yenthe666 

i have added my account to gitenterpise but still i get the error message below

Your authentication with Github has failed! Please try again.
In order to clone and install the Odoo enterprise version you
need to be an offical Odoo partner and you need access to
http://github.com/odoo/enterprise.
TIP: Press ctrl+c to stop this script.

please assist

**Comment by AcroVenom** [comment]
> 

did you try to login using your github password or a personal github token?

**Comment by AcroVenom** [comment]
> GooD morning @Yenthe666
> 
> i have added my account to gitenterpise but still i get the error message below
> 
> Your authentication with Github has failed! Please try again. In order to clone and install the Odoo enterprise version you need to be an offical Odoo partner and you need access to [http://github.com/odoo/enterprise](https://github.com/odoo/enterprise). TIP: Press ctrl+c to stop this script.
> 
> please assist

did you tried to authenticate using your github password or a personal token?

**Comment by Yenthe666** [comment]
password :)

**Comment by Darkmanzoro** [comment]
Good Morning Yenthe666

I used password initially but I got the error message after reading git
how-to then generated passcode which granted me access..

thank you
