### ISSUE TITLE
can we install odoo 15 on ubuntu 22.04

### ISSUE THREAD

**Issue by shekharmax** [Yenthe666/InstallScript#351]
we tried to install odoo 15 on ubuntu 22.04 using script but it fails

**Comment by jcdrubay** [comment]
I did a simple install of Odoo 15 on Ubuntu 22.04 successfully (not with this script).
You should share some error message so people can help you.
You might need to bump the version of Wkhtml2pdf from this script to make it work.

**Comment by Yenthe666** [comment]
Yeah please give concrete feedbacks. Technically it should work I believe. What tracebacks did you get?

**Comment by KristofOn** [comment]
Hello, I also tried to install it using the script without succes, on first look it failed to install wkhtml2pdf because the version libsl1.1 can't get downloaded on ubuntu 22.04, I installed libsl1.1 and wkhtml2pdf manually. But without result. If I find the time I will see if I find something usefull in the tracebacks. Is it allowable to run the script twice?

**Comment by KristofOn** [comment]
By the way, i also tried to install it on ubuntu 20.04 next to an existing V13 release (last year succesfully installed with the script) but without succes. V13 on port 8069, V15 on port 8070.

**Comment by cierek** [comment]
make sure you have more than 1GB ram, I have multiple instances on Ubuntu 22 running ok

**Comment by Yenthe666** [comment]
Yeah indeed it should really work but make sure the instance has enough RAM. If that is not the issue please paste logs/errors.

**Comment by intelliVersal** [comment]
Hi, @Yenthe666 i used to use your script till V13, it was extremely smooth but using it for V15 on Ubuntu 20 or 22 for both enterprise and community is not working at all. What i found so far (though not able to fix them) are multiple issues, like for example  (by the way i am running it on a very heavy duty server, 24 Cores, 64 GB RAM so not a hardware issue at all)
1). correct python version doesn't get installed at all, if somehow it (python 3) is installed then default version stays as 2.7,   
2).  A lot of libraries, dependencies doesn't get installed, i installed manually around 10-15 one by by looking at errors after that Odoo at least started creating log but Odoo doesn't work and start showing a lot of errors, 
3). sudo add-apt-repository universe  shows error.

Can you please check/test it on Ubuntu 20 or 22 for V15, even on community ? you will see the issues yourself for sure.

Note: when i followed step by step instructions mentioned on other websites like https://www.cybrosys.com/blog/how-to-install-odoo-15-on-ubuntu-2004-lts-server Odoo got installed without any problem but its very time consuming as well as don't have the coverage and robustness your script have.

**Comment by Yenthe666** [comment]
Heyhey! Sorry but it is most likely because I'm not using it as often as I'm more on other side of projects now & we tend to use Odoo.sh much more often 🤔 I'm currently not in the liberty to dedicate a lot of time to this I'm afraid..

**Comment by intelliVersal** [comment]
Ok I understand and appreciate your efforts, till V13 it saved lot of my time. Since yesterday i was trying to investigate and have one new finding, which is the Ubuntu 20.x server i initiated the script already have Python 3.8 setup on it by default but after running script somehow Python 2.7 setup on the server and is setup as default python, i don't know how.

This is just for your info.
