### ISSUE TITLE
Icon not showing on 3rd party apps

### ISSUE THREAD

**Issue by boukar10** [Yenthe666/InstallScript#375]
Hello
I installed odoo16 on Ubuntu 20.04. When I import a 3rd party apps, the icon is not showing.  Below the steps I did to install the 3rd party apps

- Download and upload to /odoo/custom/addons
- Unzip the file
- restart odoo service
- Developer mode
- Reload the ist of Apps
Then then I can see the Apps but the icon is not showing.
I even reboot my server

Please can you help?
Best Regards

**Comment by Ahmed4120** [comment]
Yes, That happend with me also, custom ADDON folder is not working, that's because it has to have at least one working module in it or any directory with `init.py` and `manifest.py` files inside it 

**How I fixed this problem?**
Before installing Odoo,I have uploaded a module to `opt` directory, then .. I have added the following to Yenthe script
after the line
`sudo su $OE_USER -c "mkdir $OE_HOME/custom/addons"`
I added
`sudo su root -c "cp -R /opt/my_module_name $OE_HOME/custom/addons"`

That will copy the module to the custom addon directory before starting Odoo, so it will work fine
