### ISSUE TITLE
wkhtmltopdf

### ISSUE THREAD

**Issue by maravento** [Yenthe666/InstallScript#42]
Great work...
Why not replace (in xenial) x86 or x64 wkhtmltopdf install (WKHTMLTOX_X64 / WKHTMLTOX_X32)  by:
 "sudo apt-get install wkhtmltopdf -y"?  (or at least update /0.12/0.12.1/wkhtmltox-0.12.1-etc-.deb to /0.12/0.12.2.1/wkhtmltox-0.12.2.1-etc-.deb)
Thanks

**Comment by Yenthe666** [comment]
Hi @maravento,

Thank you!
The reason that it is hardcoded and not "sudo apt-get install wkhtmltopdf -y" or /0.12/0.12.2.1/wkhtmltox-0.12.2.1-etc-.deb is that it is not officially supported by Odoo.
It can render some things wrong and it can give issues, so that is why it is done this way.

Regards,
Yenthe

**Comment by maravento** [comment]
Ok. I got it. Thank you for your contribution. I have tried the script and it works perfect

**Comment by Yenthe666** [comment]
You're welcome! Happy to hear it works good for you.
