### ISSUE TITLE
Can't import csv

### ISSUE THREAD

**Issue by albericyao** [Yenthe666/InstallScript#59]
Hi, 

after the installation (odoo 9.0 or 10.0), I can't validate a csv importation . How can I fix it?

**Comment by Yenthe666** [comment]
Hi @albericyao,

Please post back the output of the log right after you tried to import a CSV. I believe we might be missing a dependency for this 😉

**Comment by albericyao** [comment]
Hi @Yenthe666 
this what  I get when I a want to import

![cap](https://user-images.githubusercontent.com/29493207/31541540-884d8c1a-affe-11e7-9439-4d28df384b23.PNG)

and this is the result of the log
![cap 2](https://user-images.githubusercontent.com/29493207/31541559-9c9977d8-affe-11e7-96de-ed3134d29e66.PNG)

As you can see I can't validate the importation

**Comment by albericyao** [comment]
As you can see I can't validate the importation

**Comment by Yenthe666** [comment]
This really doesn't look related to my script though. Perhaps there is something wrong with your csv?

**Comment by albericyao** [comment]
ok I will check, thanks!

**Comment by chris001** [comment]
There were MANY missing python3 dependencies.
So this bug is PROBABLY fixed in #62  , @Yenthe666

**Comment by Yenthe666** [comment]
@albericyao it looks like I forgot/missed quite some forward fixes to P3. The probability that the commit https://github.com/Yenthe666/InstallScript/commit/c4c69b17fa55fce5585d202ec11a1159e8086785 has fixed your problem is high. Otherwise, have a look at https://github.com/Yenthe666/InstallScript/commit/c908b376b1c573adf6d159f1df104911c8faac91
