### ISSUE TITLE
[11] odoo 11 installscript not working

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#65]
After installing, odoo is not running.

With command
`/opt/odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf`

appears this error

```
 File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_mail_server.py", line 16, in <module>
    import html2text
ImportError: No module named html2text
```
html2text is impossible to install

**Comment by fgarcia-humanoide** [comment]
Worked for me doing this!!!

installscript from Yenthe 
`https://raw.githubusercontent.com/Yenthe666/InstallScript/11.0/odoo_install.sh`

Installing this

`sudo apt-get install build-essential libssl-dev libffi-dev python3-dev`

and installing this (pull request) 
`
https://github.com/Yenthe666/InstallScript/pull/62/files`

**Comment by Yenthe666** [comment]
Hi @fgarcia-humanoide,

Thank you for your report.
There where still quite some missing packages for `P3` which are fixed in the commits https://github.com/Yenthe666/InstallScript/commit/c908b376b1c573adf6d159f1df104911c8faac91, https://github.com/Yenthe666/InstallScript/commit/c4c69b17fa55fce5585d202ec11a1159e8086785 and https://github.com/Yenthe666/InstallScript/commit/1067ca0c19b44e523bb4ed9a2a2136925f19a770
The problem shouldn't happen again when you would now do another clean install on a new server. 😄 

Regards,
Yenthe

**Comment by fgarcia-humanoide** [comment]
And allso
pip3 install setuptools
